spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spring_reactive
    username: beep
    password: beep

  flyway:
    url: jdbc:postgresql://localhost:5432/spring_reactive
    user: beep
    password: beep

